---
- name: Installing required packages via apt
  apt: name="{{item}}"
       state=latest
       update_cache=yes
  with_items: "{{ apt_packages }}"
  become: yes
  become_method: sudo
  tags:
    - apache