---
- name: Detect if rubies are installed
  command: '{{ rvm_binary_path }} {{ item }} do true'
  changed_when: False
  failed_when: False
  register: detect_rubies
  with_items: '{{ rvm_rubies }}'
  when: rvm_rubies
  become: yes
  become_method: sudo
  tags:
    - rvm
    - rubies

- name: Install rubies
  command: '{{ rvm_binary_path }} install {{ item.item }} {{ rvm_ruby_install_flags }}'
  when: rvm_rubies and item.rc|default(0) != 0
  with_items: '{{ detect_rubies.results }}'
  become: yes
  become_method: sudo
  tags:
    - rvm
    - rubies

- name: Detect default ruby version
  command: '{{ rvm_binary_path }} alias list default'
  changed_when: False
  register: detect_default_ruby_version
  become: yes
  become_method: sudo
  tags:
    - rvm
    - rubies

- name: Select default ruby
  command: '{{ rvm_binary_path }} alias create default {{ rvm_default_ruby_version }}'
  when: detect_default_ruby_version.stdout|default() == '' or
        rvm_default_ruby_version not in detect_default_ruby_version.stdout
  become: yes
  become_method: sudo
  tags:
    - rvm
    - rubies

- name: Detect installed ruby patch number
  shell: >
    {{ rvm_binary_path }} list strings | grep {{ item }} | tail -n 1
  with_items: '{{ rvm_rubies }}'
  changed_when: False
  register: ruby_patch
  always_run: yes # Run even when in --check mode (http://docs.ansible.com/ansible/playbooks_checkmode.html)
  become: yes
  become_method: sudo
  tags:
    - rvm
    - rubies

- name: Install bundler if not installed
  shell: >
    ls {{ rvm_install_path }}/wrappers/{{ item.stdout }}
    | if ! grep "^bundler " ; then {{ rvm_install_path }}/wrappers/{{ item.stdout }}/gem install bundler ; fi
  args:
    creates: '{{ rvm_install_path }}/wrappers/{{ item.stdout }}/bundler'
  with_items: '{{ ruby_patch.results }}'
  register: bundler_install
  changed_when: '"Successfully installed bundler" in bundler_install.stdout'
  become: yes
  become_method: sudo
  tags:
    - rvm
    - rubies

- name: Symlink ruby related binaries on the system path
  file:
    state: 'link'
    src: '{{ rvm_install_path }}/wrappers/default/{{ item }}'
    dest: '{{ rvm_symlink_to }}/{{ item }}'
    owner: 'root'
    group: 'root'
  with_items: '{{ rvm_symlink_binaries }}'
  become: yes
  become_method: sudo
  tags:
    - rvm
    - rubies

#- name: Detect if ruby version can be deleted
#  command: '{{ rvm_binary_path }} {{ rvm_delete_ruby }} do true'
#  changed_when: False
#  failed_when: False
#  register: detect_delete_ruby != ''
#  when: rvm_delete_ruby
#  become: yes
#  become_method: sudo
#  tags:
#    - rvm
#    - rubies
#
#- name: Delete ruby version
#  command: '{{ rvm_binary_path }} remove {{ rvm_delete_ruby }}'
#  changed_when: False
#  when: rvm_delete_ruby != '' and detect_delete_ruby.rc == 0
#  become: yes
#  become_method: sudo
#  tags:
#    - rvm
#    - rubies
